[package]
name = "proxy-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.12"
once_cell = "1.17.1"
reqwest = "0.11.15"
tokio = { version = "1.0", features = ["full"] }
url = "2.3.1"
